### PR TITLE
Update addColumnFilters.ts

### PR DESCRIPTION
**Pull request by luke-hagar-sp**
Added Includes filter, can be used instead of prefix filter.

### CODE REVIEW

**Comment by luke-hagar-sp** [comment]
Hey @bryanmylee!
I hope you are having a fantastic close to your week. 

My implementation called for includes over startsWith for a column Filter so I figured I would contribute my solution should anyone else have a similar preference.

Additionally I am getting type errors when trying to use the original value on the rows, so I'm looking into fixing that right now as well

**Comment by luke-hagar-sp** [comment]
image

**Comment by bryanmylee** [comment]
Hi @luke-hagar-sp, thanks so much for your contribution! The filter functions provided by the library are just example functions, and any function that matches the function signature can be used for the filtering, so it doesn't have to be from the library.

You should be able to define that function in your own code and pass it into the plugin options just fine.

**Comment by bryanmylee** [comment]
> image

This is because each `row` is just a `BodyRow`, which could either be a `DataBodyRow` or a `DisplayBodyRow`. The `DisplayBodyRow` would not have an original data item attached to it, hence we need to check if it's a `DataBodyRow` before accessing `original`.

You can check the [`.isData()`](https://svelte-headless-table.bryanmylee.com/docs/api/body-row#isdata-boolean) method on `row` first.

```ts
row.isData() && row.original.id
```

**Comment by luke-hagar-sp** [comment]
Roger that on the filter, that's what I had done already, I guess I was just surprised the example used startsWith over includes :)

Also, Thank you for the explanation, that resolves all of my issues, fantastic work on this package by the way.

**Pull request closed without merging**
