### PR TITLE
Make `header` as column's alternative id

### LINKED ISSUE #114: Make id optional
Can we just make `id` in `table.column()` with function accessor and `table.display()` optional? Since `header` is already unique in most cases, we can use that as default value for `id`.

### PR DESCRIPTION
**Pull request by risalfajar**
Fixes #114 

I'm new into these things, so please check the code and let me know what you think.

### CODE REVIEW

**Comment by risalfajar** [comment]
Hello @bryanmylee could you check this?

**Review by bryanmylee — COMMENTED** [review]
These look great! Thanks for the PR :) I'll bump the versions and merge asap

**Comment by bryanmylee** [comment]
@risalfajar Can you update the version in `package.json` to `0.17.3`, run `npm i`, then update the PR?

**Comment by risalfajar** [comment]
Done!

**Comment by risalfajar** [comment]
Hello @bryanmylee I just noticed that the [docs](https://svelte-headless-table.bryanmylee.com/docs/api/create-columns#columndef-id-string) aren't being updated even though I've updated the .md file, is there a problem with the PR?

**Pull request merged**
